# Generated by Django 2.0.9 on 2019-04-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time on which the object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time on which the object was last modified.')),
                ('score', models.FloatField(default=0)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ride',
            name='rating',
        ),
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.ManyToManyField(related_name='rating', to='rides.Qualification'),
        ),
    ]
